from sklearn.mixture import GaussianMixture
import imageio

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
# random seed
RANDOM_SEED = 42

# Gaussian Mixture Model (GMM) Clustering
def gaussian_mixture_model(X_train_pca, X_val_pca):
    cov_types = ["full", "tied", "diag", "spherical"]
    k_range = range(20, 61, 5)
    aic_scores = {cv : [] for cv in cov_types}
    bic_scores = {cv : [] for cv in cov_types}

    # Fit multiple GMMs and record AIC/BIC
    for cv in cov_types:
        for k in k_range:
            gmm = GaussianMixture(n_components = k, covariance_type = cv, random_state = RANDOM_SEED)
            gmm.fit(X_train_pca)
            aic_scores[cv].append(gmm.aic(X_val_pca))
            bic_scores[cv].append(gmm.bic(X_val_pca))

    # Plot BIC
    plt.figure(figsize = (14,6))
    for cv in cov_types:
        plt.plot(list(k_range), bic_scores[cv], marker = 'o', label = f"BIC - {cv}")
    plt.yscale("log")
    plt.xlabel("Number of clusters (k)")
    plt.ylabel("BIC Score (lower is better)")
    plt.title("GMM Model Selection by BIC on Validation Set")
    plt.legend()
    plt.grid(alpha = 0.3)
    plt.tight_layout()
    plt.show()

    # Plot AIC
    plt.figure(figsize = (14,6))
    for cv in cov_types:
        plt.plot(list(k_range), aic_scores[cv], marker = 'o', label = f"AIC - {cv}")
    plt.yscale("log")
    plt.xlabel("Number of clusters (k)")
    plt.ylabel("AIC Score (lower is better)")
    plt.title("GMM Model Selection by AIC on Validation Set")
    plt.legend()
    plt.grid(alpha = 0.3)
    plt.tight_layout()
    plt.show()

    # Find best model
    best_cv, best_k, best_score = None, None, float('inf')
    for cv in cov_types:
        for k, score in zip(k_range, bic_scores[cv]):
            if score < best_score:
                best_score = score
                best_cv = cv
                best_k = k

    print(f"[GMM] Best by BIC -> covariance_type={best_cv}, n_components={best_k}, BIC={best_score:.2f}\n")

    # Fit best GMM
    X_trainval_pca = np.vstack([X_train_pca, X_val_pca])
    best_gmm = GaussianMixture(n_components = best_k, covariance_type = best_cv, random_state = RANDOM_SEED)
    best_gmm.fit(X_trainval_pca)

    train_labels = best_gmm.predict(X_trainval_pca)
    train_probs = best_gmm.predict_proba(X_trainval_pca)

    # result
    print("GMM cluster labels (first 10):", train_labels[:10])
    print("GMM probabilities (first sample):", train_probs[0])

    return best_gmm, best_k

# Hard & Soft Cluster
def hard_soft_cluster(best_gmm, best_k, X_test_pca):
    hard_clusters = best_gmm.predict(X_test_pca)
    soft_clusters = best_gmm.predict_proba(X_test_pca)

    print("=== Hard Cluster Assignments (first 10 samples) ===")
    print(hard_clusters[:10])
    print("\n=== Soft Cluster Assignments (first 10 samples) ===")
    print(soft_clusters[:10])

    # Save results
    df_hard = pd.DataFrame({"Image_Index" : np.arange(len(hard_clusters)), "Hard_Cluster" : hard_clusters})
    df_soft = pd.DataFrame(soft_clusters, columns = [f"Cluster_{i}" for i in range(best_k)])
    df_soft.insert(0, "Image_Index", np.arange(len(soft_clusters)))
    df_hard.to_csv("outputs/results/GMM_Hard_Clusters.csv", index = False)
    df_soft.to_csv("outputs/results/GMM_Soft_Clusters.csv", index = False)
    print("\n[INFO] Saved hard & soft clustering results to CSV files.\n")

# Generate Synthetic Faces Using GMM
def generate_synthetic_faces(best_gmm, pca):
    num_new_faces = 10
    new_faces_pca, _ = best_gmm.sample(num_new_faces)
    new_faces = pca.inverse_transform(new_faces_pca).reshape(-1, 64, 64)

    fig, axes = plt.subplots(2, 5, figsize = (12,5))
    fig.suptitle("Synthetic Faces Generated by GMM", fontsize = 16)
    for i, ax in enumerate(axes.flat):
        ax.imshow(new_faces[i], cmap = 'gray')
        ax.set_title(f"Sample {i + 1}")
        ax.axis("off")
    plt.tight_layout(rect = [0, 0, 1, 0.95])
    plt.show()

    for i, face in enumerate(new_faces):
        imageio.imwrite(f"outputs/figures/Synthetic_Face_{i + 1}.png", (face * 255).astype(np.uint8))
    print("[INFO] Synthetic faces saved as 'synthetic_face_X.png'\n")